name: Python CI

on:
  push:
  pull_request:
    branches:
      - master


jobs:
  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./be-high-level

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m venv .venv
          # Add venv to GITHUB_PATH so all future steps use it automatically
          echo "$PWD/.venv/bin" >> $GITHUB_PATH
          
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install ruff ty

      - name: Check Formatting
        run: ruff format --check .

      - name: Run Linter
        run: ruff check .

      - name: Static type checker (ty)
        run: ty check

      - name: Unit tests
        run: |
          PYTHONPATH=src python -m unittest discover tests
